Exclude columns
lumoslabs/changes_are_logged pull request #1
Opened 2016-12-19 23:01 UTC by camertron

Let's you exclude the values of specified attributes via the `automatically_log_changes` class method (which has replaced the `after_initialize` callback setup). This is useful when you want to avoid serializing a complex Ruby object like a `CarrierWave::Uploader`. Here's an example:

```ruby
class Vehicle < ActiveRecord::Base
  # the carrierwave uploader attached to the 'photo' attribute
  mount_uploader :photo, MyApp::VehiclePhotoUploader

  include ChangesAreLogged
  automatically_log_changes exclude: %w(photo)
end
```

Now `photo` won't get YAML serialized and written into the `changes_logged` column in your `change_logs` table.

2016-12-19 23:17 UTC, zvkemp requested changes

2016-12-19 23:17 UTC, zvkemp commented on lib/changes_are_logged.rb
> +        exclude_list = self.class.log_changes_options.fetch(:exclude, []).map(&:to_s)
propose using `:except`, which is a more-or-less standard option on a number of built-in rails methods

2016-12-19 23:17 UTC, zvkemp commented on lib/changes_are_logged.rb
> +        @changes_logged = self.changes.each_with_object({}) do |(attribute, value), ret|
`self.` is redundant

2016-12-19 23:17 UTC, zvkemp commented on lib/changes_are_logged.rb
> +            [nil, 'Attribute changed, but value has been excluded.']
I would expect this condition not to return a value at all — maybe there should be a `:mask` option that indicates a change was made, but the values aren't revealed in the log?

2016-12-19 23:17 UTC, zvkemp commented on lib/changes_are_logged.rb
> +      @log_changes_options = options
this won't be inherited for STI models

2016-12-19 23:22 UTC, camertron commented on lib/changes_are_logged.rb
> +      @log_changes_options = options
Is that a problem?

2016-12-19 23:22 UTC, camertron commented on lib/changes_are_logged.rb
> +            [nil, 'Attribute changed, but value has been excluded.']
Ok, `:mask` makes sense. What do you think of `:filter`?

2016-12-19 23:23 UTC, camertron commented on lib/changes_are_logged.rb
> +        @changes_logged = self.changes.each_with_object({}) do |(attribute, value), ret|
Good catch, copied/pasted from legacy.

2016-12-19 23:28 UTC, zvkemp commented on lib/changes_are_logged.rb
> +            [nil, 'Attribute changed, but value has been excluded.']
`:filter` sounds good

2016-12-19 23:29 UTC, zvkemp commented on lib/changes_are_logged.rb
> +      @log_changes_options = options
IMO yes, since the `after_initialize` block *will* be inherited, but the options won't be.

2016-12-20 23:12 UTC, zvkemp approved these changes

2016-12-20 23:18 UTC, merged