[BRD-480] Replace HashWithIndifferentAccess
lumoslabs/changes_are_logged pull request #4
Opened 2020-02-06 20:30 UTC by valikos

Replace HashWithIndifferentAccess with ActiveSupport::HashWithIndifferentAccess

2020-02-07 13:05 UTC, idanci commented on lib/changes_are_logged/version.rb
> +  VERSION = '1.2.1'
Can you also udpage changelog?

2020-02-10 18:57 UTC, andriimosin requested changes
Looks great, but please, let's make sure we didn't forget to update the Changelog

2020-02-10 19:01 UTC, valikos commented on lib/changes_are_logged/version.rb
> +  VERSION = '1.2.1'
Done.

2020-02-10 19:36 UTC, andriimosin approved these changes
Awesome! Thank you!

2020-02-10 19:43 UTC, merged